export const GETSHOES_START = 'GETSHOES_START';
export const GETSHOES_SUCCESS = 'GETSHOES_SUCCESS';
export const GETSHOES_FAIL = 'GETSHOES_FAIL';

export const GETSNEAKER_DETAILS = 'GETSNEAKER_DETAILS';
export const UPDATE_SNEAKER_SUCCESS = 'UPDATE_SNEAKER_SUCCESS';
export const ADD_SNEAKER_SUCCESS = 'ADD_SNEAKER_SUCCESS';
export const DELETE_SNEAKER_SUCCESS = 'DELETE_SNEAKER_SUCCESS';
